### ISSUE TITLE
Task list to jit `Adam.step`

### ISSUE THREAD

**Issue by shino16** [Lightning-AI/lightning-thunder#1055]
This is a list of tasks to enable compiling `Adam.step`/`AdamW.step`.

## Goal

The expected usage is:

```py
optimizer = Adam(model.parameters())
optimizer_step = jit(optimizer.step)
# or torch.compile(optimizer.step, backend=<thunder>)

for X, y in data:
  optimizer.zero_grad()
  outputs = model(X)
  loss = loss_fn(X, y)
  loss.backward()
  optimizer_step()
```

## Task list for `torch.compile(optimizer.step, backend=<thunder>)`

We have to be able to trace through PyTorch's implementation (with `foreach=False`, `fused=False`)

- [ ] Add `TensorProxy.grad` attribute and track `Tensor.grad`
- [ ] Add `torch.lerp`

## Task list for `thunder.jit(optimizer.step)`

This can be easily achieved by applying an `OperatorExecutor` to symbolically replace `Adam.step`'s inner implementation with our own thunder-friendly implementation.

- [ ] Jit `Adam.step` with a custom operator executor

However, once we are able to `torch.compile` it with Thunder backend, I expect `thunder.jit` will be able to naturally trace through `Adam.step` without patching it.

There is a trouble, however, that `Adam.step` creates tensors as its inner state on the first call and use them on subsequent calls. This behavior cannot be tracked by the current implementation of `thunder.jit`, which traces through a given function once and takes the same path on every call.

- [ ] Workaround for `Adam.step`'s lazy initialization of its inner state
