### ISSUE TITLE
Dynamic constraints and NumberProxies

### ISSUE THREAD

**Issue by jjsjann123** [Lightning-AI/lightning-thunder#262]
## 🚀 Feature

We'd like to have thunder.jit support dynamic constraints so we are not going to bake every number in a program as compile time constant. This should allow us re-use some compiled program to avoid endless recompilation with dynamic shape.

### Pitch

We'd want to:
- [x] keep Scalar input (including tensor properties like shape) as NumberProxy in the trace and feed them into compute trace as inputs.
- [x] [Partially Finished] have prologue trace to insert checks to ensure program safety.

prototyping PRs:

- [x] removing Number inheritance from derivatives of NumberProxy #286 
- [x] allow `symbolic values` cache option: #518 
- [ ] ~`symbolic values` cache option by default: #250~ shelving for priority adjustment

Issues:

- [x] number proxy is no number: #272
- [ ] ~executor specific caching rule: #263~ crossing out since this is not necessary
- [x] prim should be able to insert constraints to bake in static numbers: #463
- [ ] dynamic shape needs to be modeled in trace: #471 
- [ ] ~utils.check on NumberProxy needs to be sanitized in prim/clang/torch.~ crossing out since we might not need it in the short term. Will still follow up with a separate issue.
- [x] NumberProxy handling in grad transform: #541 (will be addressed in #244)
- [x] NumberProxy inconsistency is introduced by grad transform #541

### Progress

~NumberProxy inheritance PR merged #286.~

~Currently working on enabling caching option `symbolic values` to allow trace handling dynamic scalar inputs (WIP in PR #250). This is going to be the next milestone.~ shelving this milestone for now. Since enabling symbolic values as the default cache policy cannot be easily done without dynamic shape support in TensorProxy. Which is our immediate goal.

**Comment by jjsjann123** [comment]
As my current prototype in #250, I realized that `torch/__init__.py` has a few complexities:

1. value based control flow: https://github.com/Lightning-AI/lightning-thunder/blob/82185e3a55d5b3f0bea8a7366d74a275dbe34acd/thunder/torch/__init__.py#L953
2. there's also semantic checks: https://github.com/Lightning-AI/lightning-thunder/blob/82185e3a55d5b3f0bea8a7366d74a275dbe34acd/thunder/torch/__init__.py#L752-L753

[AIs] We need to allow language-based constraints to be injected and placed in prologue trace.

Right now I'm seeing some of those checks showing up in the compute trace and that could be excessive, but we should be able to const fold and merge some of those checks as an optimization later.

**Comment by jjsjann123** [comment]
unintentionally walked into dynamic shapes case.

https://github.com/Lightning-AI/lightning-thunder/blob/b7154dc77b5bf8a02bcbc2e56310c62fd75808ff/thunder/core/prims.py#L3102

operations inside `prims` is not traced, so we won't be able to actually have `new_shape` the way it's currently done with NumberProxies. Because the new number proxy won't be visible... The shape computation should be done at `clang` instead.

But for now we can just mark everything as constant shapes.

**Comment by jjsjann123** [comment]
Note for myself.

Some tricky shape usage in the trace that leads to control flow. https://github.com/Lightning-AI/lightning-thunder/pull/260#discussion_r1628259774

**Comment by jjsjann123** [comment]
Thanks for bringing up that. Yes it should have been able to do that.
I do have another issue tracking this specific problem. #463 

Let me move the example there.

**Comment by jjsjann123** [comment]
I'm going to close this PR for now. The one trailing issue is enable by default #250 . Which we are shelving for now and will revisit after dynamic shape is in better shape in TensorProxy.
