### ISSUE TITLE
Support NeMo StableDiffusion network

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#266]
## 🚀 Feature

NeMo's "MegatronLatentDiffusion" model implements Stable Diffusion

Initial `examine`:

`Found 37 distinct operations, of which 30 (81.1%) are supported`

### Work items

- [ ] [`mse_loss` #174](https://github.com/Lightning-AI/lightning-thunder/issues/174)
- [ ] [Implement `TensorBase.is_contiguous` #172 ](https://github.com/Lightning-AI/lightning-thunder/issues/172)
- [ ] [Implement `Tensor.type` #177 ](https://github.com/Lightning-AI/lightning-thunder/issues/177)
- [ ] Implement `TensorBase.gather`
- [ ] Implement `TensorBase.long`
- [ ] Implement `_VariableFunctionsClass.randint` of torch
- [ ] Test memory use of NeMo model with out-of-place add instead of the in-place variant

**Comment by tfogal** [comment]
Thanks Abhishree!

For:

> Test memory use of NeMo model with out-of-place add instead of the in-place variant

Are there in-place ops in use here? The task list above *appears* to be all pure operators; maybe I missed something?

**Comment by jjsjann123** [comment]
> Test memory use of NeMo model with out-of-place add instead of the in-place variant

Wondering how we are going to evaluate this one.
i.e. if we are just using eager mode for the time being, an `inplace` version does save memory footprint, but that might not translate to a compiled program. Since we *might* have a chance to fuse `out-of-place` operation.

**Comment by tfogal** [comment]
> > Test memory use of NeMo model with out-of-place add instead of the in-place variant
> 
> Wondering how we are going to evaluate this one. i.e. if we are just using eager mode for the time being, an `inplace` version does save memory footprint, but that might not translate to a compiled program. Since we _might_ have a chance to fuse `out-of-place` operation.

Yeah, it's definitely not an apples-to-apples comparison.

But actually that's not the comparison we're interested in here. Here we'd want to evaluate NeMo alone (i.e. w/o thunder) using in-place ops vs. NeMo alone using out-of-place ops.

While we can always modify any network to use Thunder (and this is the approach I would recommend to most users!), NeMo isn't going to adopt Thunder instantly. First we need to show some value to NeMo.

Until then, the NeMo team is happy to consider changes that make networks more amenable to Thunder, but only if they improve or at least do not regress non-Thunder-based use cases.

Does that make help/make sense?

**Comment by jjsjann123** [comment]
> Until then, the NeMo team is happy to consider changes that make networks more amenable to Thunder, but only if they improve or at least do not regress non-Thunder-based use cases.

Got'ya. That makes sense. I guess that's also why the last item doesn't have a corresponding thunder issue. Sorry for the noise.
