### ISSUE TITLE
Support NeMo Vision Transformer Model

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#333]
🚀 Feature

NeMo's VitClassificationModel implements a vision transformer.

Initial `examine`:
`Found 33 distinct operations, of which 26 (78.8%) are supported`

### Work items

- [ ] [`TensorBase.is_cuda` #329](https://github.com/Lightning-AI/lightning-thunder/issues/329)
- [ ] [`_VariableFunctionsClass.baddbmm` of torch #326](https://github.com/Lightning-AI/lightning-thunder/issues/326)
- [ ] [`device` of torch #327](https://github.com/Lightning-AI/lightning-thunder/issues/327)
- [ ] [`TensorBase.view_as` #328](https://github.com/Lightning-AI/lightning-thunder/issues/328)
- [ ] [`TensorBase.expand_as` #330](https://github.com/Lightning-AI/lightning-thunder/issues/330)
- [ ] [`_VariableFunctionsClass.empty of torch` #331](https://github.com/Lightning-AI/lightning-thunder/issues/331)
- [ ] [`_set_grad_enabled` of torch._C #332](https://github.com/Lightning-AI/lightning-thunder/issues/332)

cc @tfogal
