### ISSUE TITLE
Support NeMo NeVa Model

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#343]
### 🚀 Feature

NeMo's NeVa (LLaVa) is a multimodal language model

Initial `examine`:
`Found 49 distinct operations, of which 39 (79.6%) are supported`

### Work items
- [ ] [`_VariableFunctionsClass.empty` of torch #331 ](https://github.com/Lightning-AI/lightning-thunder/issues/331)
- [ ] [`device` of torch](https://github.com/Lightning-AI/lightning-thunder/issues/327)
- [ ] [`_VariableFunctionsClass.max` of torch #338 ](https://github.com/Lightning-AI/lightning-thunder/issues/338)
- [ ] [`TensorBase.view_as` #328 ](https://github.com/Lightning-AI/lightning-thunder/issues/328)
- [ ] [`_VariableFunctionsClass.baddbmm` of torch](https://github.com/Lightning-AI/lightning-thunder/issues/326)
- [ ] [`TensorBase.is_complex` #339 ](https://github.com/Lightning-AI/lightning-thunder/issues/339)
- [ ] [`TensorBase.div_` #340 ](https://github.com/Lightning-AI/lightning-thunder/issues/340)
- [ ] [`TensorBase.__setitem__` #341](https://github.com/Lightning-AI/lightning-thunder/issues/341)
- [ ] [`TensorBase.clone` #342 ](https://github.com/Lightning-AI/lightning-thunder/issues/342)
- [ ] [`TensorBase.is_cuda` #329 ](https://github.com/Lightning-AI/lightning-thunder/issues/329)

cc @tfogal

**Comment by IvanYashchuk** [comment]
Can you share the script for the `examine` call?

**Comment by tfogal** [comment]
> Can you share the script for the `examine` call?

@athitten when you have a minute

**Comment by athitten** [comment]
Adding the updated command to use `megatron_amp_O2=True` and model.mcore_gpt = True (NeMo models will be defaulting to using models from Megatron, hence this setting). With `megatron_amp_O2=True`, having precision=bf16 should do mixed precision training with main copy of weights in FP32, but just to be safe also specifying precision=bf16-mixed.

```python
python3 ./examples/multimodal/multimodal_llm/neva/neva_pretrain.py trainer.precision=bf16-mixed model.megatron_amp_O2=True model.mcore_gpt=True  trainer.num_nodes=1 trainer.devices=1 trainer.val_check_interval=10 trainer.limit_val_batches=5 trainer.log_every_n_steps=1 ++exp_manager.max_time_per_run=00:00:03:00 trainer.max_steps=20 model.micro_batch_size=2 model.global_batch_size=4 model.tensor_model_parallel_size=1 model.pipeline_model_parallel_size=1 exp_manager.create_checkpoint_callback=False model.data.data_path=./data/multimodal/tiny-neva/dummy.json model.data.image_folder=./data/multimodal/tiny-neva/images model.tokenizer.library=sentencepiece model.tokenizer.model=./data/multimodal/tiny-neva/tokenizer_add_special.model model.num_layers=2 model.hidden_size=5120 model.ffn_hidden_size=13824 model.num_attention_heads=40 model.normalization=rmsnorm model.data.num_workers=0 model.data.conv_template=llama_2 model.mm_cfg.vision_encoder.from_pretrained=openai/clip-vit-large-patch14 model.mm_cfg.llm.from_pretrained=null model.use_flash_attention=false exp_manager.exp_dir=./foo-neva-train
```

**Comment by athitten** [comment]
This might be helpful: The full config with default values for all parameters can be found: [here](https://github.com/NVIDIA/NeMo/blob/main/examples/multimodal/multimodal_llm/neva/conf/neva_config.yaml). Only the parameters we specify in the run command get overwritten by the specified values and others default to values mentioned in the config.

**Comment by tfogal** [comment]
> Adding the updated command

Thanks, @athitten !
I have edited the original issue to _mostly_ reflect the updated command. Unfortunately #753 blocks setting `model.mcore_gpt=True`, so for now that one's still `False`... but let's prioritize that one!

**Comment by athitten** [comment]
Yes its important to prioritize getting thunder working with `mcore_gpt=True` as it will be default for NeMo models once we deprecate the legacy path.
