### ISSUE TITLE
Support NeMo MegatronGPTModel

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#344]
### 🚀 Feature

Support NeMo's LLM `MegatronGPTModel`

Initial examine:
Found 44 distinct operations, of which 33 (75%) are supported
### Work items

- [ ] [`TensorBase.div_` #340 ](https://github.com/Lightning-AI/lightning-thunder/issues/340)
- [ ] [`TensorBase.__setitem__` #341 ](https://github.com/Lightning-AI/lightning-thunder/issues/341)
- [ ] [`device` of torch #327 ](https://github.com/Lightning-AI/lightning-thunder/issues/327)
- [ ] [`TensorBase.clone` #342 ](https://github.com/Lightning-AI/lightning-thunder/issues/342)
- [ ] [`TensorBase.view_as` #328 ](https://github.com/Lightning-AI/lightning-thunder/issues/328)
- [ ] [`_set_grad_enabled` of torch._C #332 ](https://github.com/Lightning-AI/lightning-thunder/issues/332)
- [ ] [`TensorBase.is_cuda` #329 ](https://github.com/Lightning-AI/lightning-thunder/issues/329)
- [ ] [`TensorBase.is_complex` #339 ](https://github.com/Lightning-AI/lightning-thunder/issues/339)
- [ ] [`_VariableFunctionsClass.empty` of torch #331 ](https://github.com/Lightning-AI/lightning-thunder/issues/331)
- [ ] [`_VariableFunctionsClass.max` #338 ](https://github.com/Lightning-AI/lightning-thunder/issues/338)
- [ ] [`_VariableFunctionsClass.baddbmm` of torch #326 ](https://github.com/Lightning-AI/lightning-thunder/issues/326)

cc @tfogal
